version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Deploying Static Website..."
      - aws cloudformation deploy --template-file static-site.yaml --stack-name static-website --capabilities CAPABILITY_IAM
  post_build:
    commands:
      - echo "Deployment complete!"
